# Generated by Django 3.2.11 on 2022-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Nothing')], null=True),
        ),
    ]
