# Generated by Django 3.2.11 on 2022-01-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('peach', models.BooleanField(default=False)),
                ('bean', models.BooleanField(default=False)),
                ('pork', models.BooleanField(default=False)),
                ('beef', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
