# Generated by Django 3.2.11 on 2022-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='buckwheat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='chicken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='crab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='mackerel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='peanut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='pineNut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='shellfish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='shrimp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='squid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='sulfite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='tomato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='walnut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allergy',
            name='wheat',
            field=models.BooleanField(default=False),
        ),
    ]
